### ISSUE TITLE
não estou conseguindo usar o pacote

### ISSUE THREAD

**Issue by drepalma** [jorgeguto/ComexstatR#1]
Olá jorgeguto! Estou tentando usar o pacote, mas sem sucesso. Poderia me ajudar? 
Obrigada
 Andreza

**Comment by jorgeguto** [comment]
Olá, drepalma. Posso sim. 

Poderia descrever o problema que está tendo, de preferência com um exemplo de código.

Att.
Jorge

**Comment by drepalma** [comment]
Oi Jorge,

muito obrigada pela criação do pacote.
Eu consegui instalar, mas quando fui tentar usar o exemplo que está no
github, obtive a seguinte mensagem de erro:

Error in pesquisar_comex_stat(ano_inicial = 2018, ano_final = 2018,
mes_inicial = 1,  :
  não foi possível encontrar a função "pesquisar_comex_stat"


E esse aqui:

> pesquisar_comex_stat(ano_inicial = 2018, ano_final = 2018, mes_inicial =
1, mes_final = 12,
+                      tipo_op = 'exp', tipo_ord = 'val', filtros =
c('pais'), detalhamentos = c('pais','ncm'),
+                      filtros_esp = list(c(160,249)))
Error in pesquisar_comex_stat(ano_inicial = 2018, ano_final = 2018,
mes_inicial = 1,  :
  não foi possível encontrar a função "pesquisar_comex_stat"

Agradeço se puder me auxiliar.
Abraços
Andreza

Em ter., 4 de mai. de 2021 às 15:43, jorgeguto ***@***.***>
escreveu:

**Comment by jorgeguto** [comment]
Para usar as funções é necessário que o pacote seja carregado, para isso basta executar o comando:

_library(ComexstatR)_

**Comment by drepalma** [comment]
Nossa Jorge, esqueci do library! hehe Foi a pressa em testar o pacote!

Os dados disponíveis no pacote já são os revisados com a mudança de
metodologia?

Vou tentar fazer mais algumas pesquisas e te retorno se tiver dúvidas.

Muito obrigada
Abraços
Andreza

Em ter., 4 de mai. de 2021 às 16:14, jorgeguto ***@***.***>
escreveu:

**Comment by jorgeguto** [comment]
Os dados são consultados em tempo real (equivale a uma consulta feita na página do comexstat), não fica nada armazenado no pacote em si.  Assim estão sempre atualizados com o que é disponibilizado.
