### ISSUE TITLE
Acesso a api comex

### ISSUE THREAD

**Issue by beghini21** [jorgeguto/ComexstatR#3]
Opa, tudo bom ?

  Você sabe me dizer onde eu posso encontrar a documentação dos filtros dos pedidos da API do comexstat ? reparei no código que o pacote se conecta a esse link "http://api.comexstat.mdic.gov.br/cities?filter=", mas sei como ficaria o link final, com os respectivos filtros.

Atenciosamente,
Victor

**Comment by jorgeguto** [comment]
Olá,
Não tive acesso à documentação da API e não sei se existe em algum lugar. Esse pacote foi feito analisando as requisições http que a página do ComexStat utiliza ao fazermos uma consulta e imitando essas requisições.

Att.
Jorge

**Comment by beghini21** [comment]
Opa,

Muito obrigado pelo retorno, muito interessante essa metodologia.

Att,
Victor
